# Generated by Django 2.1.3 on 2022-11-13 17:20

from django.db import migrations, models
import photos.utils


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20190102_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(upload_to=photos.utils.photo_directory_path),
        ),
    ]
